# Generated by Django 5.0.2 on 2024-03-04 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_material_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='customer',
            new_name='client',
        ),
        migrations.AddField(
            model_name='invoicematerial',
            name='item',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AddField(
            model_name='invoicematerial',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
