# Generated by Django 5.0.2 on 2024-03-06 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_customer_invoice_client_invoicematerial_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicematerial',
            name='item',
        ),
        migrations.RemoveField(
            model_name='invoicematerial',
            name='price',
        ),
    ]
