# Generated by Django 5.0.2 on 2024-03-07 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_invoice_line_items'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invoicematerial',
            unique_together={('invoice', 'material')},
        ),
    ]
