# Generated by Django 5.0.2 on 2024-03-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_invoice_invoice_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_to_name', models.CharField(max_length=100, null=True)),
                ('ship_to_address', models.CharField(max_length=255, null=True)),
                ('ship_to_city', models.CharField(max_length=100, null=True)),
                ('ship_to_state', models.CharField(max_length=100, null=True)),
                ('ship_to_zip', models.CharField(max_length=20, null=True)),
                ('email_address', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('contact_name', models.CharField(max_length=100)),
                ('markup_value', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='item_description',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='price',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='quantities',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='ship_to_address',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='ship_to_name',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='terms',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='total',
        ),
        migrations.AddField(
            model_name='invoicematerial',
            name='markup',
            field=models.BooleanField(default=0),
        ),
    ]
