# Generated by Django 5.0.2 on 2024-03-23 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_userinfo_delete_event_remove_invoice_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='contact_name',
        ),
    ]
