# Generated by Django 5.0.2 on 2024-03-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_userinfo_contact_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='invoice_terms',
            field=models.TextField(blank=True, max_length=20),
        ),
    ]
