# Generated by Django 4.2.2 on 2024-02-24 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_event_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='name',
        ),
    ]
