# Generated by Django 4.2.2 on 2024-02-24 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_event_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=100)),
                ('email', models.EmailField(default='Unknown', max_length=254)),
                ('contact_name', models.CharField(default='Unknown', max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('address_street', models.CharField(default='Unknown', max_length=255)),
                ('address_city', models.CharField(default='Unknown', max_length=100)),
                ('address_state', models.CharField(default='Unknown', max_length=100)),
                ('address_zip', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
