# Generated by Django 5.0.2 on 2024-02-25 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_invoice_balance_due_invoice_bill_to_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='name',
        ),
        migrations.AddField(
            model_name='client',
            name='FName',
            field=models.CharField(default='text', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='LName',
            field=models.CharField(default='test2', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='address_city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='address_state',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='address_street',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
