# Generated by Django 5.0.2 on 2024-02-27 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_client_name_client_fname_client_lname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Proposal', 'Proposal'), ('Open', 'Open'), ('Closed', 'Closed')], default='Draft', max_length=10),
        ),
    ]
