# Generated by Django 5.0.2 on 2024-03-04 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_invoicematerial_delete_invoice_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='quantity',
        ),
    ]
