# Generated by Django 5.0.2 on 2024-03-06 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_invoicematerial_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='line_items',
            field=models.ManyToManyField(through='core.InvoiceMaterial', to='core.material'),
        ),
    ]
