# Generated by Django 5.0.2 on 2024-03-07 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_invoicematerial_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_number',
        ),
    ]
